# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 17:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('chu_iChurchID', models.AutoField(primary_key=True, serialize=False)),
                ('chu_sName', models.CharField(blank=True, max_length=80, verbose_name='Name')),
                ('chu_sStreet', models.CharField(blank=True, max_length=80, verbose_name='Street')),
                ('chu_sCity', models.CharField(blank=True, max_length=32, verbose_name='City')),
                ('chu_sState', models.CharField(blank=True, choices=[('OR', 'OR'), ('WA', 'WA')], max_length=2, verbose_name='State')),
                ('chu_sPostalCode', models.CharField(blank=True, max_length=10, verbose_name='Zip')),
                ('chu_sPhone', models.CharField(blank=True, max_length=12, verbose_name='Phone')),
                ('chu_sEmailAddress', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('chu_sURLWebsite', models.CharField(blank=True, max_length=255, verbose_name='Website')),
                ('chu_sMissionStatement', models.CharField(blank=True, max_length=255, verbose_name='Mission Statement')),
                ('chu_sMemo', models.CharField(blank=True, max_length=255, verbose_name='Memo')),
            ],
            options={
                'ordering': ('-chu_sName',),
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fam_iFamilyID', models.AutoField(primary_key=True, serialize=False, verbose_name='Family #')),
                ('fam_sStreet', models.CharField(max_length=80, verbose_name='Street')),
                ('fam_sCity', models.CharField(choices=[('Beaverton', 'Beaverton'), ('Portland', 'Portland'), ('Vancouver', 'Vancouver')], max_length=32, verbose_name='City')),
                ('fam_sState', models.CharField(choices=[('OR', 'OR'), ('WA', 'WA')], max_length=2, verbose_name='State')),
                ('fam_sPostalCode', models.CharField(max_length=10, verbose_name='Zip')),
                ('fam_sPhone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='[0-9]{10}')], verbose_name='Phone')),
                ('fam_sFamilyEligibility', models.CharField(choices=[('registered', 'Thuộc Giáo Xứ'), ('unregistered', 'Không Thuộc Giáo Xứ')], default='registered', max_length=10, verbose_name='Eligibility')),
                ('fam_dtEntry', models.DateField(auto_now_add=True, verbose_name='Entry Date')),
                ('fam_dtExit', models.DateField(blank=True, null=True, verbose_name='Exit Date')),
                ('fam_oPortrait', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Portrait')),
                ('fam_iChurchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lavang.Church', verbose_name='Parish')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_iMemberID', models.AutoField(primary_key=True, serialize=False, verbose_name='Member #')),
                ('mem_sChristianName', models.CharField(blank=True, max_length=40, verbose_name='Tên Thánh')),
                ('mem_sFirstName', models.CharField(max_length=20, verbose_name='Tên Gọi')),
                ('mem_sLastName', models.CharField(max_length=20, verbose_name='Tên Họ')),
                ('mem_sMiddleName', models.CharField(blank=True, max_length=20, verbose_name='Tên Đệm')),
                ('mem_sMemberRole', models.CharField(choices=[('unknown', 'Unknown'), ('head', 'Chủ Gia Ðình'), ('grandparent', 'Ông Bà'), ('husband', 'Chồng'), ('wife', 'Vợ'), ('child', 'Con'), ('grandchild', 'Cháu')], default='unknown', max_length=20, verbose_name='Member Role')),
                ('mem_dtDayOfBirth', models.DateField(verbose_name='Ngày Sanh')),
                ('mem_sCityOfBirth', models.CharField(blank=True, max_length=32, verbose_name='City of Birth')),
                ('mem_sCountryOfBirth', models.CharField(blank=True, max_length=18, verbose_name='Country of Birth')),
                ('mem_sGender', models.CharField(choices=[('Male', 'Trai'), ('Female', 'Gái')], default='male', max_length=10, verbose_name='Gender')),
                ('mem_sNationality', models.CharField(blank=True, max_length=10, verbose_name='Nationality')),
                ('mem_sMartialStatusID', models.CharField(choices=[('unknown', 'Unknown'), ('married', 'Lập Gia Ðình'), ('single', 'Ðộc Thân'), ('serve', 'Ði Tu')], default='unknown', max_length=20, verbose_name='Marital Status')),
                ('mem_sMobile', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='[0-9]{10}')], verbose_name='Mobile')),
                ('mem_sEmailAddress', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('mem_dtEntry', models.DateField(auto_now_add=True, verbose_name='Entry Date')),
                ('mem_dtExit', models.DateField(blank=True, null=True, verbose_name='Exit Date')),
                ('mem_sMemo', models.CharField(blank=True, max_length=255, verbose_name='Memo')),
                ('mem_oPortrait', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Portrait')),
                ('mem_iFamilyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='+', to='lavang.Family', verbose_name='Family #')),
            ],
        ),
    ]
